FROM python:latest
# Create an app directory for this application to run
RUN mkdir /app
RUN apt-get update
RUN python -m pip install --upgrade pip
COPY ./ /app
WORKDIR /app
RUN pip install -r requirements.txt